import React, { useState } from 'react';
import { Video, Plus, Play, Trash2, Bot } from 'lucide-react';
import VideoProfileSetup from './VideoProfileSetup';

interface VideoResponse {
  id: string;
  question: string;
  videoBlob: Blob;
  timestamp: string;
}

const VideoProfileManager = () => {
  const [responses, setResponses] = useState<VideoResponse[]>([]);
  const [isRecording, setIsRecording] = useState(false);

  // Common interview questions generated by AI based on job requirements
  const commonQuestions = [
    "Tell me about your experience with React and modern frontend development.",
    "Describe a challenging project you've worked on and how you overcame obstacles.",
    "How do you approach learning new technologies and staying current in your field?"
  ];

  const handleSaveResponse = (videoBlob: Blob) => {
    const newResponse: VideoResponse = {
      id: Date.now().toString(),
      question: commonQuestions[responses.length],
      videoBlob,
      timestamp: new Date().toISOString()
    };
    setResponses([...responses, newResponse]);
    setIsRecording(false);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-semibold">Video Profile Responses</h2>
        {responses.length < commonQuestions.length && (
          <button
            onClick={() => setIsRecording(true)}
            className="flex items-center space-x-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
          >
            <Plus className="w-4 h-4" />
            <span>Add Response</span>
          </button>
        )}
      </div>

      {isRecording && (
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-6">
          <VideoProfileSetup
            question={commonQuestions[responses.length]}
            onSave={handleSaveResponse}
          />
        </div>
      )}

      <div className="grid grid-cols-1 gap-4">
        {responses.map((response) => (
          <div
            key={response.id}
            className="bg-white dark:bg-gray-800 rounded-lg p-4 flex items-center justify-between"
          >
            <div className="flex items-center space-x-4">
              <div className="p-2 bg-indigo-100 dark:bg-indigo-900 rounded-lg">
                <Video className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
              </div>
              <div>
                <p className="font-medium">{response.question}</p>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Recorded {new Date(response.timestamp).toLocaleDateString()}
                </p>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <button
                onClick={() => {
                  const url = URL.createObjectURL(response.videoBlob);
                  window.open(url);
                }}
                className="p-2 text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-200"
              >
                <Play className="w-5 h-5" />
              </button>
              <button
                onClick={() => {
                  setResponses(responses.filter(r => r.id !== response.id));
                }}
                className="p-2 text-red-600 hover:text-red-700"
              >
                <Trash2 className="w-5 h-5" />
              </button>
            </div>
          </div>
        ))}
      </div>

      {responses.length === 0 && !isRecording && (
        <div className="text-center py-12">
          <Video className="w-12 h-12 mx-auto text-gray-400 mb-4" />
          <p className="text-gray-600 dark:text-gray-400">
            No video responses yet. Add your first response to enhance your profile.
          </p>
        </div>
      )}

      {responses.length > 0 && (
        <div className="bg-indigo-50 dark:bg-indigo-900/30 rounded-lg p-4">
          <div className="flex items-center space-x-2 mb-2">
            <Bot className="w-5 h-5 text-indigo-600" />
            <span className="font-medium">AI Insight</span>
          </div>
          <p className="text-gray-600 dark:text-gray-400">
            Your video responses will be automatically included with relevant job applications,
            increasing your chances of standing out to employers.
          </p>
        </div>
      )}
    </div>
  );
};

export default VideoProfileManager;